CREATE TABLE CONTACTS (ID INT, FIRST_NAME VARCHAR, LAST_NAME VARCHAR, EMAIL VARCHAR, PHONE_NUMBER VARCHAR, PRIMARY KEY (id));
INSERT INTO CONTACTS (ID,FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER)
VALUES (1,'GUILLERMO','SÁEZ GÓMEZ','guillermosaezgomez@gmail.com','+32483994103');